components/calendar.vue

Check if event's end day is in current selected day

Fix filter event day

---

pages/_campus/rides/index.vue

Fix car select dropdown to show only one scroll (modal) instead of two (dropdown + modal)

Fix car select dropdown to show only one scroll

---

api/rides.js
components/form/search-available-car.vue
pages/_campus/rides/index.vue

The first car on the list is also the last one used

Select by default last car used by driver

---

components/calendar.vue
package-lock.json

fix bug ride duration < 30 min was display on wrong range

Change starting date for a new ride at current time.

---

pages/_campus/history.vue

Fix rides fetch (dates)

---

components/planning/calendar.vue
components/planning/modal.vue
components/ride-calendar/index.vue

Improve dropdown visibility on planning modal

Remove events count indicators in month view

---

components/ride-calendar/index.vue

Fix planificateur intervals. Works with multiple and/or overlaping slots

---

components/ride-calendar/index.vue

I dont like this but at least it works...

Fix planificateur overflow

---

CHANGELOG.md
components/planificator/index.vue
components/sidemenu.vue

Minor fix css overflow for planificator tooltip

Fix fetch ride when selecting a base

---

CHANGELOG.md
components/planning/cars/modal.vue

Fixed dropdown title

---

CHANGELOG.md
components/dashboard/statuses.vue

Round percents on dashboard

---

CHANGELOG.md
components/planificator/index.vue

Change relative to fix arrow margin

---

CHANGELOG.md
pages/_campus/cars/index.vue
pages/_campus/phones/index.vue
pages/_campus/pois/index.vue
pages/_campus/users/index.vue
pages/car-models/index.vue
pages/phone-models/index.vue
pages/pois/index.vue
pages/users/index.vue

Fixed links to update items

---

CHANGELOG.md
pages/_campus/pois/index.vue
pages/pois/index.vue

Fixed emojis for pois lists

---

CHANGELOG.md
components/crud/list.vue
pages/ratings/index.vue

Updated ratings label and resolved minor bug with list.vue

---

CHANGELOG.md
components/dashboard/statuses.vue

Added translation to status

---

CHANGELOG.md
components/form/search-user-campus.vue
components/sidemenu.vue
pages/_campus.vue
store/context.js
store/realtime.js

Added red dot notification for rides to validate

---

pages/_campus/edit.vue
pages/campuses/_id/edit.vue

Fixed reservationScope display

---

CHANGELOG.md
components/modals/cars-planning.vue
components/modals/drivers-planning.vue
pages/_campus/cars/_id/edit.vue
pages/_campus/drivers/_id/edit.vue
pages/_campus/edit.vue
pages/_campus/history.vue
pages/_campus/phones/_id/edit.vue
pages/_campus/pois/_id/edit.vue
pages/_campus/users/_id/edit.vue
pages/account.vue
pages/campuses/_id/edit.vue
pages/car-models/_id/edit.vue
pages/categories/_id/edit.vue
pages/feedback.vue
pages/login.vue
pages/phone-models/_id/edit.vue
pages/pois/_id/edit.vue
pages/users/_id/edit.vue

Add trim where it's relevant

---

CHANGELOG.md
components/modals/import-csv.vue
pages/_campus/pois/index.vue
pages/_campus/users/index.vue
pages/campuses/_id/edit.vue
pages/users/index.vue

Add missing message on user deletion

---

CHANGELOG.md
pages/campuses/_id/edit.vue

Reservation scope can be set in days on base creation

---

CHANGELOG.md
pages/_campus/phones/index.vue
pages/_campus/pois/index.vue
pages/_campus/users/index.vue

Add missing right checks

---

CHANGELOG.md
pages/_campus/history.vue

Fixed driver name display in history table

---

.gitlab-ci.yml
CHANGELOG.md
package-lock.json
pages/login.vue

Added alert message if browser is not Firefox

---

CHANGELOG.md
components/form/campuses.vue
components/sidemenu.vue
helpers/requestable.js
package.json
pages/dashboard.vue

Added dashboard.vue for multi bases

---

CHANGELOG.md
components/crud/filter.vue
components/crud/header.vue
components/crud/mixins/handle-filters-campus-users.js
components/crud/mixins/handle-filters.js
helpers/format-coordinates.js
pages/_campus/cars/index.vue
pages/_campus/phones/index.vue
pages/_campus/pois/index.vue
pages/_campus/users/index.vue
pages/campuses/index.vue
pages/car-models/index.vue
pages/categories/index.vue
pages/phone-models/index.vue
pages/pois/index.vue
pages/users/index.vue

Added crud filter

---

CHANGELOG.md
components/charts/average.vue
components/dashboard/mixins/background-colors.js
components/dashboard/ratings.vue
components/sidemenu.vue
package.json
pages/_campus/dashboard.vue
pages/_campus/ratings/_id.vue
pages/_campus/ratings/index.vue
pages/_campus/rides/_id.vue

Full feature with new pages, stats on dashboard.vue and fixes according to PR comments
Checklist

Ratings workflow updated

---

package-lock.json
pages/dashboard.vue

hotfix : ratings for root dashboard.vue added

---

CHANGELOG.md
pages/car-models/_id/edit.vue
pages/car-models/index.vue

Added capacity to car-model crud

---

pages/_campus/cars/index.vue
pages/_campus/users/index.vue

Hotfix roles access

---

CHANGELOG.md
pages/_campus/planificator/index.vue
store/realtime.js

Fixed setRides to avoid keeping wrong campuses rides in rides list

---

components/planificator/index.vue

Fixed condition to prevent null value on car model

---

components/crud/stops-table.vue
pages/_campus/drivers/_id.js
pages/_campus/drivers/_id/edit.vue
pages/_campus/users/_id.js
pages/_campus/users/_id/edit.vue

Hotfix button icon and user edit page to add licences selection

---

pages/_campus/drivers/_id/edit.vue
pages/_campus/users/_id/edit.vue

Hotfix :
- Remove licences management to random users
- Remove deadcode : isDriver from users/_id/edit.vue
- Fixed condition for drivers to display component on creation

Hotfix users creation

---

components/crud/stops-table.vue
components/form/selects/shuttle-factories.vue
components/form/selects/stops.vue
pages/_campus/history.vue
pages/_campus/rides/_id.vue
pages/_campus/shuttle-factories/_id/edit.vue
pages/_campus/shuttle-factories/index.vue
pages/dashboard.vue
plugins/context.js

Fixes according to tests on 13th may

---

package-lock.json
package.json

update lib-vue version

---

components/form/search-poi.vue
components/map.vue
components/modals/planificator/shuttle.vue
pages/_campus/cars/_id/edit.vue
pages/_campus/cars/index.vue
pages/_campus/phones/_id/edit.vue
pages/_campus/phones/index.vue
pages/_campus/planning/cars.vue
pages/_campus/pois/_id/edit.vue
pages/_campus/pois/index.vue
pages/_campus/shuttle-factories/index.vue

Fixed queries to match campuses routes

---

components/modals/planificator/ride.vue
components/modals/planificator/shuttle.vue
pages/_campus/cars/_id.js
pages/_campus/cars/index.vue
pages/_campus/phones/_id.js
pages/_campus/phones/index.vue
pages/_campus/planning/cars.vue
pages/_campus/pois/_id.js
pages/_campus/pois/index.vue
pages/_campus/ratings/_id.vue
pages/_campus/ratings/index.vue
pages/_campus/shuttle-factories/_id.js
pages/_campus/shuttle-factories/index.vue
pages/_campus/users/index.vue
store/realtime.js

- Modal close on success on shuttle creation and edit
- Access to POI local CRUD given to regulator
- Added setCampus to CampusCRUD queries
- Fixed red not notification

Fixed bug report on 22.05.2020

---

components/form/selects/stops.vue
components/modals/planificator/ride.vue
components/modals/planificator/shuttle/stops-manager.vue
components/planificator/index.vue
pages/_campus/drivers/_id/edit.vue

- Dynamic display for shuttle stops
- Added count indicator for rides to validate in planificator calendar
- Fixed licences select display onInput
- Added errors mixin to ride modal

[WIP] Fix linked to tests on 26.05.2020
